@echo off
echo Running git status...
git status
echo Setting remote URL to https://github.com/Sudhanshu-Malhotra/BANK-MANAGEMENT.git
git remote set-url origin https://github.com/Sudhanshu-Malhotra/BANK-MANAGEMENT.git 2>nul
if %errorlevel% neq 0 git remote add origin https://github.com/Sudhanshu-Malhotra/BANK-MANAGEMENT.git
echo Adding files...
git add .
echo Committing...
git commit -m "Update code"
echo Moving to main branch...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
echo Done!
